#!/bin/bash


if [ "$EUID" -ne 0 ]
    then echo "This installation requires root privilege to execute"
    exit
fi

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PATH_SAVE=/opt/easynordvpn
PATH_EXEC=/usr/local
EXEC_RUN=$PATH_EXEC/bin
EXEC_ICON=$PATH_EXEC/share/icons
EXEC_MENU=$PATH_EXEC/share/applications
SAVE_NAME=$PATH_SAVE/easynordvpn.py
RUN_NAME=$EXEC_RUN/easynordvpn
ICON_NAME=/easynordvpn.png
MENU_NAME=/easynordvpn.desktop

mkdir -p $PATH_SAVE
mkdir -p $EXEC_RUN
mkdir -p $EXEC_ICON
mkdir -p $EXEC_MENU

cp -R --remove-destination $SCRIPT_DIR/* $PATH_SAVE/ > /dev/null 2>&1
chmod +x $SAVE_NAME
ln -s $SAVE_NAME $RUN_NAME
cp ${PATH_SAVE}${ICON_NAME} ${EXEC_ICON}${ICON_NAME}
cp ${PATH_SAVE}${MENU_NAME} ${EXEC_MENU}${MENU_NAME}
